import {
  Atom,
  BadgeDollarSign,
  BarChart3,
  Binary,
  BookMarked,
  BookOpen,
  BookText,
  Bot,
  Brain,
  BriefcaseBusiness,
  Calculator,
  ChartNoAxesColumnIncreasing,
  Clock3,
  Code2,
  Coins,
  Compass,
  Cpu,
  Database,
  Divide,
  Dna,
  Drama,
  Dumbbell,
  Earth,
  FlaskConical,
  FunctionSquare,
  Gavel,
  Globe2,
  GraduationCap,
  HeartPulse,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  LineChart,
  Map as MapIcon,
  Microscope,
  MonitorCog,
  Music2,
  NotebookPen,
  Palette,
  PenTool,
  PencilRuler,
  Percent,
  Pilcrow,
  Puzzle,
  Quote,
  Rocket,
  Ruler,
  Scale,
  School,
  ScrollText,
  Shapes,
  Sigma,
  SpellCheck,
  SquareFunction,
  Telescope,
  TestTube2,
  type LucideIcon,
} from "lucide-react";

export interface SubjectIconOption {
  value: string;
  label: string;
  Icon: LucideIcon;
}

export const SUBJECT_ICON_OPTIONS: SubjectIconOption[] = [
  { value: "book", label: "Buku Klasik", Icon: BookOpen },
  { value: "book-open", label: "Buku Terbuka", Icon: BookOpen },
  { value: "book-text", label: "Buku Teks", Icon: BookText },
  { value: "book-marked", label: "Buku Bertanda", Icon: BookMarked },
  { value: "library", label: "Perpustakaan", Icon: Library },
  { value: "notebook-pen", label: "Buku Catatan", Icon: NotebookPen },
  { value: "languages", label: "Bahasa", Icon: Languages },
  { value: "spell-check", label: "Ejaan", Icon: SpellCheck },
  { value: "pilcrow", label: "Paragraf", Icon: Pilcrow },
  { value: "quote", label: "Kutipan", Icon: Quote },
  { value: "calculator", label: "Kalkulator", Icon: Calculator },
  { value: "sigma", label: "Sigma", Icon: Sigma },
  { value: "square-function", label: "Fungsi Matematika", Icon: SquareFunction },
  { value: "function-square", label: "Persamaan", Icon: FunctionSquare },
  { value: "percent", label: "Persentase", Icon: Percent },
  { value: "divide", label: "Pembagian", Icon: Divide },
  { value: "ruler", label: "Penggaris", Icon: Ruler },
  { value: "compass", label: "Jangka", Icon: Compass },
  { value: "pencil-ruler", label: "Geometri", Icon: PencilRuler },
  { value: "atom", label: "Atom / Fisika", Icon: Atom },
  { value: "flask-conical", label: "Labu Kimia", Icon: FlaskConical },
  { value: "test-tube", label: "Tabung Reaksi", Icon: TestTube2 },
  { value: "microscope", label: "Mikroskop", Icon: Microscope },
  { value: "dna", label: "DNA / Biologi", Icon: Dna },
  { value: "leaf", label: "Lingkungan", Icon: Leaf },
  { value: "earth", label: "Bumi", Icon: Earth },
  { value: "globe", label: "Geografi", Icon: Globe2 },
  { value: "map", label: "Peta", Icon: MapIcon },
  { value: "landmark", label: "Sejarah", Icon: Landmark },
  { value: "scroll-text", label: "Naskah Sejarah", Icon: ScrollText },
  { value: "clock", label: "Waktu", Icon: Clock3 },
  { value: "brain", label: "Penalaran", Icon: Brain },
  { value: "lightbulb", label: "Ide", Icon: Lightbulb },
  { value: "puzzle", label: "Logika", Icon: Puzzle },
  { value: "shapes", label: "Bentuk", Icon: Shapes },
  { value: "chart-up", label: "Statistika", Icon: ChartNoAxesColumnIncreasing },
  { value: "bar-chart", label: "Diagram Batang", Icon: BarChart3 },
  { value: "line-chart", label: "Diagram Garis", Icon: LineChart },
  { value: "binary", label: "Biner", Icon: Binary },
  { value: "code", label: "Pemrograman", Icon: Code2 },
  { value: "laptop", label: "Komputer", Icon: Laptop },
  { value: "monitor-cog", label: "Teknologi", Icon: MonitorCog },
  { value: "cpu", label: "Prosesor", Icon: Cpu },
  { value: "database", label: "Basis Data", Icon: Database },
  { value: "bot", label: "Robotika / AI", Icon: Bot },
  { value: "rocket", label: "Antariksa", Icon: Rocket },
  { value: "telescope", label: "Astronomi", Icon: Telescope },
  { value: "graduation-cap", label: "Akademik", Icon: GraduationCap },
  { value: "school", label: "Sekolah", Icon: School },
  { value: "pen-tool", label: "Menulis", Icon: PenTool },
  { value: "palette", label: "Seni Rupa", Icon: Palette },
  { value: "music", label: "Musik", Icon: Music2 },
  { value: "drama", label: "Drama", Icon: Drama },
  { value: "dumbbell", label: "Olahraga", Icon: Dumbbell },
  { value: "heart-pulse", label: "Kesehatan", Icon: HeartPulse },
  { value: "scale", label: "Hukum", Icon: Scale },
  { value: "gavel", label: "Kewarganegaraan", Icon: Gavel },
  { value: "badge-dollar", label: "Ekonomi", Icon: BadgeDollarSign },
  { value: "coins", label: "Keuangan", Icon: Coins },
  { value: "briefcase", label: "Bisnis", Icon: BriefcaseBusiness },
];

const SUBJECT_ICON_MAP = new Map(
  SUBJECT_ICON_OPTIONS.map((option) => [option.value, option.Icon]),
);

interface SubjectIconProps {
  name?: string | null;
  className?: string;
}

export function SubjectIcon({ name, className = "h-4 w-4" }: SubjectIconProps) {
  const Icon = (name && SUBJECT_ICON_MAP.get(name)) || BookOpen;
  return <Icon className={className} />;
}
